[workspace]
members = [
    "crates/pathweave-core",
    "crates/pathweave-transport-quic",
    "crates/pathweave-transport-ble",
    "crates/pathweave-uniffi",
    "examples/pw-chat",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dancode-188/pathweave"
rust-version = "1.75"

[workspace.dependencies]
# async
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync", "io-util", "macros", "time"] }
futures = "0.3"
bytes = "1"
async-trait = "0.1"

# errors
thiserror = "2"

# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# crypto
snow = "0.10"
blake3 = "1"
bs58 = "0.5"
x25519-dalek = { version = "2", features = ["static_secrets"] }

# transports
quinn = "0.11"
rcgen = "0.13"
btleplug = "0.11"
bluer = { version = "0.17", features = ["full"] }
uuid = "1"

# ffi
uniffi = "0.28"

# cli
clap = { version = "4", features = ["derive"] }

# bundle protocol
bp7 = { version = "0.10", default-features = false }

# entropy
getrandom = "0.2"

# discovery
mdns-sd = "0.11"
if-addrs = "0.13"

# tui
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }

# testing
proptest = "1"
