[package]
name = "pathweave-transport-quic"
description = "QUIC transport for Pathweave"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pathweave-core = { path = "../pathweave-core" }
tokio = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
quinn = { workspace = true }
rcgen = { workspace = true }
mdns-sd = { workspace = true }
getrandom = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
